name: Label1 CD 워크플로우

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  label1-job:
    # job 레벨에서 직접 라벨 조건 확인
    if: contains(github.event.pull_request.labels.*.name, 'label1')
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: Label1 작업 실행
        run: |
          echo "Label1 작업 시작"
          # 여기에 Label1에 대한 실제 작업 추가
