# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  log-test:
    runs-on: ubuntu-latest # macOS 대신 Ubuntu 사용 가능
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print a simple log
        run: echo "Hello, GitHub Actions! This is a test log."

      - name: Display environment variables
        run: env

      - name: Simulate a simple script
        run: |
          echo "This is a multi-line script."
          echo "You can run basic shell commands here."
